<?xml version="1.0"?>
<package format="3">
  <name>insta360_x5_media_ros2</name>
  <version>0.1.0</version>
  <description>Official Insta360 MediaSDK real-time stitching bridge for ROS 2.</description>
  <maintainer email="aiwei@example.com">lianaiwei deployment</maintainer>
  <license>Proprietary-SDK-Adapter</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
