fastlio2_go2_adapter:
  ros__parameters:
    imu_topic: "/imu/data"
    odom_topic: "/Odometry"
    cloud_topic: "/cloud_registered_body"
    output_odom_topic: "/Odometry_go2"
    output_cloud_topic: "/cloud_registered_go2_body"
    initialization_samples: 200
    max_initial_gyro_rad_s: 0.03
    imu_t_lidar: [-0.011, -0.02329, 0.04412]
    imu_R_lidar: [1.0, 0.0, 0.0,
                  0.0, 1.0, 0.0,
                  0.0, 0.0, 1.0]
    lidar_t_body: [0.0, 0.32, -0.10]
    lidar_R_body: [0.68566663, -0.00967062, -0.72785146,
                   -0.00967062, 0.99970248, -0.02239272,
                   0.72785146, 0.02239272, 0.68536911]
